#!/bin/sh

#DEBHELPER#

set -e

USER="daemon"

echo "Setting up microblob example data at /usr/local/share/microblob"

mkdir -p /usr/local/share/microblob
if id -u $USER > /dev/null 2>&1; then
    chown ${USER}:${USER} /usr/local/share/microblob
fi
